### ISSUE TITLE
Feature #1: User can see a diary preview.

### ISSUE THREAD

**Issue by SeungjooKimSJ** [SeungjooKimSJ/somewhere-btw-blog-and-diary#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can see their diary list (which is a diary preview) page.
The current year and month are displayed in the center of the header. 
Users can see the previous month and next month's diary if press the arrow button on both sides.
On this page, users can sort out their diary lists in the latest order and old order. 
In addition, filtering according to diary emotions can be used to retrieve only the corresponding result values.
If the user presses the diary in the diary list, they can see the matching Id's diary in detail.
If the user presses the edit button, they can modify the matching Id's diary.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Add a function that can increase or decrease the month by 1 if the user clicks the left and right arrows in the header.
Users can organize their diary in the latest & oldest order, and also, good & bad feeling diary using filters.
Possible to derive the result of two filters interacting with each other.
If the user presses the Write a New Diary and Edit Diary button in the diary list, can go to the page that fits that button.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

will be added later...

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Nothing to do in this issue.

### ☁️ Server

- [x] Nothing to do in this issue.

### ⚡ Client

- [x] Create a Route Paths so that users can see the results that fit each page.
- [x] Check useParams searchParams and useNavigate whether the expected result value was derived.
- [x] Update component to match the result of what users selected.

### 🧑‍⚕️ Clean Up

- [x] Add fonts, images icon and checked them look fine.
- [x] Setting buttons and header components are commonly used on all pages and styled on.
- [x] Set up the layout styles on each media query.
- [x] Create a button that responds to a click event and use the join method to see if the results fit each type.
- [x] Use the reducer function to give a value for each state.
- [x] Use the new Date to mark the year and month in the header.
- [x] Create a function that decreases and increases the number of months if the user clicks the arrow button on the header.
- [x] Check whether the home component is given the correct value using dummy data.
- [x] Add a feature that uses the map method to create a button in which the diary is organized in the latest and oldest order.
- [x] Add a feature that uses the filter method to check whether the result value according to the diary motion is retrieved.
- [x] Check whether the two buttons interact with each other properly with dummy data.
- [x] Create a button that responds by clicking that navigate to a page where can create a new diary.
- [x] Displaying on a diary list page containing emotions, dates, content previews, and an edit button, as shown in the example.
- [x] Check if users can go to the page that fits each Id when they click on the specific diary list.
- [x] Remove all console logs, comment out code or CSS properties that have no effect.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both desktop and mobile screens.
