### ISSUE TITLE
Feature #6: User can store diary history.

### ISSUE THREAD

**Issue by SeungjooKimSJ** [SeungjooKimSJ/somewhere-btw-blog-and-diary#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can store diary history in localStorage.
Able to save it as localStorage when the user writes a diary.
Optimize the app using React Developer Tools.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Using the if statement, make a diary is stored in the localData and gets the value using JSON parse.
Use the sort method to organize the data in order and increase the current value of the id by 1 from the stored id value.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

will be added later...

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Check if the diary is stored in the localStorage.

### ☁️ Server

- [x] Nothing to do in this issue.

### ⚡ Client

- [x] Output the warning msg when the user access the non-exist diary then sends it back to the diary list page.
- [x] Update component to match the result of what users selected.

### 🧑‍⚕️ Clean Up

- [x] Check the next id value in the localStorage is increased by 1.
- [x] Check if the rendering is done well using React Dev Tools.
- [x] Change the app to render only when necessary using React Memo to improve app performance.
- [x] Check whether the title of each page is appropriately changed.
- [x] Remove all console logs, comment out code or CSS properties that have no effect.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both desktop and mobile screens.
