### ISSUE TITLE
Feature #2: User can write a new diary.

### ISSUE THREAD

**Issue by SeungjooKimSJ** [SeungjooKimSJ/somewhere-btw-blog-and-diary#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can write a new diary.
The default value of the calendar is set to the current date and the user can change the date.
Today's mood default value is set to so-so, and the background color matches the emotion color when the user presses the emoticon.
Users can increase and decrease the size of the diary text area vertically.
Press the Cancel and Save buttons to go to the Diary List page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Using Navigate function, press the back and cancel buttons to move to the previous page.
If the users press the save button, will go to the diary list page and apply the onCreate function so that the saved diary is updated.
Add the onCreate function so that the saved diary is updated when the user presses the save button that guides to the diary list page.
Using the handleClickEmotion function, convert the emotion value when clicking the emotion and make the background color match the emotion color.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

will be added later...

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Nothing to do in this issue.

### ☁️ Server

- [x] Nothing to do in this issue.

### ⚡ Client

- [x] Check useParams searchParams and useNavigate whether the expected result value was derived.
- [x] Update component to match the result of what users selected.

### 🧑‍⚕️ Clean Up

- [x] Add fonts, images icon and checked them look fine.
- [x] Add a click responds back button on the header of the write a new diary page that navigates to the previous page.
- [x] Add a calendar on the write a new diary page and check that able to change the date values.
- [x] Check the value of the emotion to see if the selected emotion is set.
- [x] Add style that changes the selected emotion's background color to the same color.
- [x] Add a text area that can only be changed vertically.
- [x] Create a back button that navigates to the previous page when pressing the cancel button.
- [x] Create a button that navigates to the diary list page when pressing the save button and check if the diary list page updates a new diary.
- [x] Add a function that prevents from coming to the previous page if users come to the diary list by pressing the save button.
- [x] Remove all console logs, comment out code or CSS properties that have no effect.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both desktop and mobile screens.
