### ISSUE TITLE
Feature #3: User can edit a diary.

### ISSUE THREAD

**Issue by SeungjooKimSJ** [SeungjooKimSJ/somewhere-btw-blog-and-diary#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can edit a diary.
Bring the corresponding diary data to the Edit page that matches the id of the diary that clicked.
When the user presses the save button after editing, the value is updated to show the diary list page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a function that possible to edit only the diaries of id in the diary list using the targetDiary and if statements.
Using the originData state, bring up the data in the diary that want to modify.
Add if statement in the handleSubmit function to distinguish whether the save button modifies or writes a new diary.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

will be added later...

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Nothing to do in this issue.

### ☁️ Server

- [x] Nothing to do in this issue.

### ⚡ Client

- [x] Update component to match the result of what users selected.
- [x] Output the warning msg when the user access the non-exist diary then sends it back to the diary list page.

### 🧑‍⚕️ Clean Up

- [x] Modify the onEdit function so the user can get the values of the diary you want to modify.
- [x] Check if the data in the diary the user wants to modify matches the Edit Component.
- [x] Add a function that the users can only change the diary if the targetDiary is on the diary list.
- [x] Check that brings up the diary that corresponds to the id want to modify.
- [x] Check if update the modified results in the diary list when the user clicks the save button on the Edit page.
- [x] Remove all console logs, comment out code or CSS properties that have no effect.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both desktop and mobile screens.
