### ISSUE TITLE
Feature #4: User can see the diary detail.

### ISSUE THREAD

**Issue by SeungjooKimSJ** [SeungjooKimSJ/somewhere-btw-blog-and-diary#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can see the diary detailed page.
Retrieve the value if the targetDiary exists and if not, send it back to the diary list.
Confirm that can move to the corresponding page if press each button on the header.
Check if the contents of the selected diary match the existing values.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Bring up the saved diary’s value using currentEmotionData.emotion_img, currentEmotionData.emotion_descript, data.content.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

will be added later...

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Nothing to do in this issue.

### ☁️ Server

- [x] Nothing to do in this issue.

### ⚡ Client

- [x] Output the warning msg when the user access the non-exist diary then sends it back to the diary list page.
- [x] Update component to match the result of what users selected.

### 🧑‍⚕️ Clean Up

- [x] Confirm if the target diary exists, then bring up the value of the diary, if not, check that is sent back to the diary list.
- [x] Use the getStrDate to check whether the date of the selected diary is showing on the header.
- [x] Check that navigates to the corresponding page if press buttons on the header.
- [x] Check the emotion's value of the saved diary and match the style as shown in the example.
- [x] Confirm the saved diary’s values are matching with the currentEmotionData.emotion_img, currentEmotionData.emotion_descript, data.content.
- [x] Remove all console logs, comment out code or CSS properties that have no effect.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both desktop and mobile screens.
