### ISSUE TITLE
Feature #5: User can delete a diary.

### ISSUE THREAD

**Issue by SeungjooKimSJ** [SeungjooKimSJ/somewhere-btw-blog-and-diary#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can delete a diary.
Pressing the delete button in the Edit page's header brings up a warning msg.
If the diary is successfully deleted then moves to the diary list page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Using the handleRemove function, a warning msg appears when the user presses the Delete button.
When the user deletes a diary, will go to the diary list page then make it impossible to go to the previous page using the Back button.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

will be added later...

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Nothing to do in this issue.

### ☁️ Server

- [x] Nothing to do in this issue.

### ⚡ Client

- [x] Output the warning msg when the user access the non-exist diary then sends it back to the diary list page.
- [x] Update component to match the result of what users selected.

### 🧑‍⚕️ Clean Up

- [x] Create the Delete button on the Edit page’s header that can remove a diary.
- [x] Put the warning msg if the user clicks the Delete button.
- [x] Check if the user successfully deletes a diary, will navigate to the diary list page.
- [x] Remove all console logs, comment out code or CSS properties that have no effect.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both desktop and mobile screens.
